### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by clmcgrath** [squaredinfinity/VSCommands#2]
promised 2015 soon support several months ago,  is this actually going to happen in the near future, even a beta release?

**Comment by maroy1986** [comment]
It's coming soon. 

https://twitter.com/vscommands/status/655802205707091968

Follow his twitter account for more updates :)

**Comment by squaredinfinity** [comment]
not dead at all, slow start but will get there!
sorry for all the delays.

**Comment by Stevoni** [comment]
Is there a possibility for the previous versions source to be placed in a branch here so others can help with the re-write?

**Comment by maroy1986** [comment]
To me, this project is officially dead... So glad I didn't paid a licence
few months ago.

**Comment by DimitarCC** [comment]
Yup this is dead and it appears the owner does not want to supply us with the code so to continue his development. at least he need to officially says that this is dead!!!!!!

**Comment by streamtree** [comment]
No tweets since December 2015, no updates to the source code in 2 months, and now the web site is down.

**Comment by gandarez** [comment]
+1

**Comment by SuperJMN** [comment]
Please, release the code if you don't want to continue developing it. Thanks in advance!

**Comment by jtmunn** [comment]
+1

**Comment by gandarez** [comment]
Opening the website today I see an error, is that the end??

http://vscommands.squaredinfinity.com/

**Comment by mikeloeven** [comment]
Can confirm that the Squared Infinity website is still offline

**Comment by gandarez** [comment]
:-1:

**Comment by mcenal** [comment]
@gandarez The reason why the project died was because of the fact that Microsoft
changed the api design in the back end from VS 2013 to VS 2015 so a number
of commands that the old one used will outright fail and if you actually
tried to install that and run it you would get an error immediately.

It is too bad the project died, I wish he would release the source. He
wanted to make money off of it (nothing wrong with that) but there isn't a
whole ton of money in that space he was working in.

**Comment by kemmis** [comment]
@mcenal The 2015 version source is all here on github from what I understand. Are you wanting him to post the 2013 source?

**Comment by mcenal** [comment]
I didn't realize the entire source was there. I guess we'll have to fix this project, but will the community be able to do it before the next version of VS comes out?

**Comment by kemmis** [comment]
btw, one thing i noticed when trying to build the solution - you'll also need to pull down the other project he has on github and build / reference them in the main solution, as this project depends on those libraries: https://github.com/squaredinfinity

I don't recall if I actually got everything to build or not. Give it a shot and let me know if you actually get it working. I'd be happy to help work on the extension if you want to setup a fork of this one for us to use.

**Comment by alexvilper** [comment]
I don't think this project is dead. If someone had bothered to look, there are new (from 3 days ago) commits **[to the Dev branch](https://github.com/squaredinfinity/VSCommands/commits/dev)** , which means they are working on it.

**Comment by squaredinfinity** [comment]
Hi everybody,

First apologies for not replying for a long time. Life got in a way, had another baby, went back to Uni, hardly had time for anything really.

Short story is that yes, api has changed so much in certain areas that a lot of code is not usable with 15. Old code used internal MS classes which aren't there anymore. Now that uni exams are behind me I'm going to invest more time in 2015 version and hopefully get a release soon. It will never be exact port of old functionality, but hopefully new useful things will come out of it.

Website is down, I'm aware of that. Basically discountasp.net changed something to the config and were massively unhelpful in fixing it. I'm planning to move to different host at some point, but to be honest would like to focus next few months on extension itself rather than the website (so expect it to be down for a while).

Again, terribly sorry for keeping you all in the dark all this time. Next release planned sometime in July.

Thank you,
Jarek

**Comment by squaredinfinity** [comment]
@kemmis referenced libs should be pulled via NuGet, not looked at main branch for long time so will double check that though.

**Comment by squaredinfinity** [comment]
As for capability going forward, MS had made many changes to how extensions are developed, with sdk dependencies being pulled via NuGet I believe that as long as there's no more poking of internal types it should be much easier to move to newer version's of VS.

**Comment by luis-fss** [comment]
I used to love this extension... Any news?

**Comment by tomzorz** [comment]
Bumpity bump.

**Comment by gandarez** [comment]
It's sad

**Comment by NKnusperer** [comment]
Do we may get Visual Studio 2017 support?

**Comment by gandarez** [comment]
@NKnusperer there's no support for VS 2015 neither VS 2017!

**Comment by clmcgrath** [comment]
Time to fork maybe if someone is up to updating?

**Comment by tomzorz** [comment]
The thing is, the whole extension API set completely changed from vs 2013 to 2015 and up - rewriting it is a very big task :(

**Comment by dyslexicanaboko** [comment]
Is there anything the community can do to get this project back on route?

**Comment by mikeloeven** [comment]
Well it is a open source git project so anyone who wants to can fork it

**Comment by dyslexicanaboko** [comment]
Yes, I was thinking about doing that, but what about the ultimate pull request? I will get started anyhow because I love this plugin and I have used it since version 1. I'm said it isn't available because it filled a lot of gaps in VS.

**Comment by clmcgrath** [comment]
closing this,  tired of seeing it in my issues feed and i have moved on

**Comment by weitzhandler** [comment]
Shame this project died like this.

**Comment by maroy1986** [comment]
I think people need to get over it... It's been like 2 years, there's plenty of alternatives tools to replace it. I've been a die hard fan of this extension back then but I found alternatives to almost any things it brings so at the end I'm not missing it that much. That was just great because everything was inside one package.

**Comment by weitzhandler** [comment]
Run **Project** without debugging. It's lack is so frustrating.

**Comment by gandarez** [comment]
I love this extension and can't believe it died

**Comment by John5965948** [comment]
What was so good about this extension?

**Comment by DimitarCC** [comment]
It doesn't matter what were good because it is dead. Almost all of the functionality of it can be found via another extensions.

**Comment by John5965948** [comment]
I found this project only today. Can you recommand useful extensions in general?

**Comment by DimitarCC** [comment]
Well it depends what do you want to use. I assume you know what was this extension for and what were included tools.
For the structure highlighting - Supercharger (free for non commercial use)
For the Subversion badges - Codinion (free)
For the codeblock end tagger - CodeBlockEndTag (free)
For the output windows - VisualBuild, VsColorOutput, Supercharger
For the debugging enhancments - OzCode (paid but have free license for opensource projects)

P.S. You can try Viasfora too because it is useful.

**Comment by John5965948** [comment]
Thank you for this list. I will check those out as I'm always interested in things that makes programming easier. 
Actually I do not know what VSCommands was for. I ended-up here today looking for creating a file that sits next to a .Designer.cs file in Visual Studio. ( https://stackoverflow.com/questions/223249/can-i-create-a-file-that-sits-next-to-a-designer-cs-file-in-visual-studio ). 
Can you recommand an extension for this?

**Comment by John5965948** [comment]
I found the FileNesting extension : https://marketplace.visualstudio.com/items?itemName=MadsKristensen.FileNesting

**Comment by WernerCD** [comment]
Does any addons exist that mimic the ability to RunAs another user? I don't see that in the list of "secondary" extensions. (VS 2015)

https://stackoverflow.com/a/3704942/409025
